urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Example:
    # I dont know what this does?? but if I take it out... it doesnt work
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
#   (r'^$', 'django.contrib.auth.views.login'),
    (r'^$', 'views.landing'),
    (r'^accounts/', include('registration.urls')),
    (r'^support/', 'views.support'),
    url(r'^theme/(?P<name>\w+)/', 'views.theme', name='theme'),
    (r'^tinymce/', 'views.tinymce'),
    (r'^tos/', 'views.tos'),
    (r'^mathplosion-dev/', 'views.dev'),
    (r'^mathplosion-users/', 'views.users'),
    (r'^videos/demo/', 'views.demovideo'),
    (r'^videos/tags/', 'views.tagsvideo'),
    (r'^videos/helpvideos/', 'views.helpvideos'),
    (r'^accounts/', include('registration.urls')),
    (r'^accounts/profile/$', 'views.loggedin'),
    (r'^accounts/logout', 'views.logout_view'),
    (r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
    (r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),
    (r'^editor/', include('editor.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

editor/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from taggit.models import (TaggedItemBase, GenericTaggedItemBase, TaggedItem,
    TagBase, Tag)
from django.db.models.signals import post_save

class MpTag(TagBase):
    user = models.ForeignKey(User, editable=False, null=True)
    description = models.TextField()

class MpTaggedItem(GenericTaggedItemBase):
    user = models.ForeignKey(User, editable=False, null=True)
    tag = models.ForeignKey(MpTag, related_name="%(app_label)s_%(class)s_items")

    def __init__(self, *args, **kwargs):
        super(MpTaggedItem, self).__init__(*args, **kwargs)
        self.user = self.content_object.user

class AbstractBase(models.Model): 
    user = models.ForeignKey(User, editable=True)
    name = models.CharField(blank=True,max_length=100, null=True)
    filename = models.CharField(blank=True,max_length=100, null=True)
    position = models.IntegerField(editable=False, blank=True, null=True)
    tags = TaggableManager(through=MpTaggedItem, blank=True) 

    def tags_ordered_by_name(self):
        return self.tags.all().order_by('name')

    def add_tag(self, tag_string):
        tag, created = MpTag.objects.get_or_create(name=tag_string)
        if created:
            tag.user = self.user
            tag.save()
        self.tags.add(tag) 
        return       

    def replace_tags(self, taglist):
        self.tags.clear() 
        for tag in taglist:
            self.add_tag(tag)
        return       

    def replace_tags_csv(self, tags_csv):
        #remove white space
        tags_csv = ''.join(tags_csv.split())

        #make it a list 
        taglist = tags_csv.split(",")
        self.replace_tags(taglist)
        return       

    class Meta:
        ordering = ['position']
        abstract = True 

class List(AbstractBase):

    def problems(self):
        return self.problem_set.all().order_by('position')

    def __unicode__(self):
        return u"List %s" % (self.name)

class AbstractProblem(AbstractBase):
    params = models.TextField(blank=True,null=True) 
    question = models.TextField(blank=True,null=True)
    answer = models.TextField(blank=True,null=True)
    javascript = models.TextField(blank=True,null=True)

    class Meta:
        abstract = True 

class Template(AbstractProblem):
    question_template = models.TextField(blank=True,null=True)
    answer_template = models.TextField(blank=True,null=True)

    def tags_ordered_by_name(self):
        return self.tags.all().order_by('name')

    def __unicode__(self):
        return u"Template %s id: %s " % (self.name,self.id)

class Problem(AbstractProblem):
    list = models.ForeignKey(List, editable=False)
    template = models.ForeignKey(Template, blank=True, editable=False)

    def get_problem_type(self):
        return self.template.name

    def __unicode__(self):
        return u"Problem %s" % (self.id)

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        user = instance
        try: 
            user.get_profile()
        except UserProfile.DoesNotExist:
            if not user.is_staff:
                print "Creating a profile for the user: ", user.username
                UserProfile.objects.create(user=user)

post_save.connect(create_user_profile, sender=User)

class UserProfile(models.Model):
    user = models.OneToOneField(User)

templates/ajax_list.html
{% load editor_extras %}
{%if mode != "edit" %}
<div class="blackwhite">
<ol>
{% endif %}

{% for problem in problems %}
{%if mode == "edit" %}
<div class="problemwrapper">
<div class="row-fluid">
    <div class="span6">
        <div class="problemtitle">
            <h4>{{ problem.name }}</h4>
        </div>
    </div>

    <div class="span6">
        <div class="btn-group pull-right">
          <a id="trigger{{problem.id}}" class="btn btn-small trigger" title="Show/Hide Answer">
            {% icon "icon-plus" %} </a>

          <a class="btn btn-small" title="Edit This Problem" href="{% url editor.views.edit_problem problem.id %}">
            {% icon "icon-pencil" %} Edit</a>

          <a class="btn btn-small ajax_link" title="Make a Copy of This Problem" href="{% url ajax_copy_problem pid=problem.id %}">
            {% icon "icon-copy"%} Copy</a>

          <a class="btn btn-small ajax_link" title="Move This Problem Up" href="{% url ajax_move_problem pid=problem.id direction="up" %}">
            {% icon "icon-arrow-up" %} </a>

          <a class="btn btn-small ajax_link" title="Move This Problem Down" href="{% url ajax_move_problem pid=problem.id direction="down" %}">
            {% icon "icon-arrow-down" %} </a>

          <a class="btn btn-small btn-warning ajax_link" title="Delete This Problem" href="{% url ajax_delete_problem pid=problem.id%}">
            {% icon "icon-remove" %} </a>

        </div> <!-- end btn group --> 
    </div>
</div> <!--row-fluid-->
{% else %}
<li>
{% endif %}

<div id="problem{{problem.id}}" class="problem blackwhite">
    <div class="question">
       {{problem.question|safe}}
    </div>

    {%if mode == "edit" or mode == "full" %}
    <div id="target{{problem.id}}" class="answerwrapper" {%if mode == "edit" %} style="display:none" {% endif %}>
        <h5 class="blackwhite" >Answer </h5>
            <div class="answer">
                {{problem.answer|safe}}
            </div>
    </div>
    {% endif %}
</div> <!--problem -->

{%if mode == "edit"%}
</div> <!--problem wrapper-->
{% else %}
</li>
{% endif %}

{% endfor %}

{%if mode != "edit" %}
</ol>
</div>
{% endif %}

templates/edit_problem_main.html
{% extends "parametrized_problem_main.html" %}
{% load editor_extras %}

{% block mainjs %}
<script type="text/javascript" src="/media/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="/media/tinymce/jscripts/tiny_mce/plugins/autoresize/editor_plugin.js"></script>

<script type="text/javascript"> 

function setup_pagecontent() {
    //we have nothing to do
}

function init_editor(id) {
    var textarea_id = id + "_textarea";
    var selector = "#" + id;
    var textarea_selector = selector + "_textarea";
    var textarea = '<textarea id="' + textarea_id + '" style="width:100%;display:none"></textarea>'
    $(selector).before(textarea);
    tinyMCE.execCommand('mceAddControl', false, textarea_id);
}

function show_editor(id) {
  var textarea_id = id + "_textarea";
  var selector = "#" + id;
  var textarea_selector = selector + "_textarea";

  // Yuck, set a global for mathplosion.js
  set_editing_mode(id,true); 

  //Get the div html, hide the div
  var html = $(selector).html();
  $(selector).hide();

  //Show the textarea
  $(textarea_selector).show();

  //Toggle the mce editor and pass in the html.
  tinyMCE.execCommand('mceToggleEditor',false,textarea_id);
  tinyMCE.get(textarea_id).setContent(html);
  //tinyMCE.get(textarea_id).dom.loadCSS("{{me
}

function hide_editor(id) {
  var selector = "#" + id;
  var textarea_id = id + "_textarea";
  var textarea_selector = selector + "_textarea";

  //Get the html out, hide the editor 
  var html = tinyMCE.get(textarea_id).getContent(html);
  tinyMCE.execCommand('mceToggleEditor',false,textarea_id);

  //Hide the textarea
  $(textarea_selector).hide();

  //put the html in the div, and show it 
  $(selector).html(html);
  $(selector).show();

  // Yuck, set a global for mathplosion.js
   set_editing_mode(id,false); 
}

function set_editing_mode (id, mode) {
  if(id === "question" && mode === true) {
     mathplosion_editquestion = true;
  }
  else if(id === "question" && mode === false) {
     mathplosion_editquestion = false;
  }
  else if(id === "answer" && mode === true) {
     mathplosion_editanswer = true;
  }
  else if(id === "answer" && mode === false) {
     mathplosion_editanswer = false;
  }
}

$(document).ready(function() {

    //var reload_opts ="?" + new Date().getTime();

      var theme_url = "{% bootstrap_css_path %}"

      //theme_url += reload_opts; 
      var mp_theme_url = "/media/mce_problemstyle.css";
      //mp_theme_url += reload_opts; 

      tinyMCE.init({ 
              theme : "advanced",
              //plugins: "fullscreen", 
              plugins: "autoresize", 
              width: "100%",
              content_css : theme_url + "," + mp_theme_url,
//            content_css : theme_url + "?" + new Date().getTime(),
              convert_urls: false,
              theme_advanced_buttons1 : "bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,fontselect,fontsizeselect",
              theme_advanced_buttons2 : ",undo,redo,|,link,unlink,image,code,|,bullist,numlist,|,outdent,indent,|,forecolor,backcolor",
              theme_advanced_buttons3 : "",
              theme_advanced_buttons4 : "",
              theme_advanced_toolbar_align : "left",
              theme_advanced_toolbar_location : "top",
              theme_advanced_statusbar_location : "bottom",
              theme_advanced_resizing: true,
              theme_advanced_resizing_min_width: 320,
              theme_advanced_resize_horizontal : true
          });

      init_editor("question");
      init_editor("answer");

   var editquestion_btn = $('#editquestion_btn');
   editquestion_btn.click(function()    {
      var icon = $(this).find('i')
      if (icon.hasClass('icon-plus')) {
          icon.removeClass('icon-plus');
          icon.addClass('icon-minus');
          mathplosion_editquestion = true;
          show_editor("question");
      }
      else if (icon.hasClass('icon-minus')) {
          icon.removeClass('icon-minus');
          icon.addClass('icon-plus');
          hide_editor("question");
          mathplosion_editquestion = false;
      }
    });

   var editanswer_btn = $('#editanswer_btn');
   editanswer_btn.click(function(){
        var icon = $(this).find('i')

        if (icon.hasClass('icon-plus')) {
            icon.removeClass('icon-plus');
            icon.addClass('icon-minus');
            mathplosion_editanswer = true;
            show_editor("answer");
        }
        else if (icon.hasClass('icon-minus')) {
            icon.removeClass('icon-minus');
            icon.addClass('icon-plus');
            hide_editor("answer");
            mathplosion_editanswer = false;
        }
    });

  //Hook up to the submit event
  $('#form').submit(function() {

    if(mathplosion_editquestion === true){ 
        hide_editor("question");
    }

    if(mathplosion_editanswer === true) {
        hide_editor("answer");
    }

   //Get the html from the div and put in the hidden input of the form
    update();
     $('#id_question').val($("#question").html());
     $('#id_answer').val($("#answer").html());
     $('#id_params').val(JSON.stringify(json_params));
  });

//Disable the enter key
  $("input").keypress(function (e) {
      var k = e.which;
      if (k == 13) {
          return false;
      }
  });

});
</script>
{{block.super}}
{% endblock mainjs %}

{% block pageform %}
{% if list %}
<form id="form" class="well form-inline" method="post" action="{% url editor.views.save problem.id %}">
{% else %}
<form id="form" class="well form-inline" method="post" action="{% url editor.views.generate_one problem.id %}">
{% endif %}
{% csrf_token %}

<!-- Here are the hidden fields -->
{{problemform.params}} 
{{problemform.question}} 
{{problemform.answer}} 

<!-- First row of the form -->
<div class="row-fluid">
    <div class="span12">
        <div id="formparams">
        <!-- params will be put in via jquery by mathplosion.js -->
        </div>
    </div>
</div>

<!-- Second row of the form -->
<div class="row-fluid">
    <div class="span12">
    {% if list %}
    <input class="btn btn-primary" type="submit" value="Save Problem" /> 
    <a class="btn" title="Finished" href="{% url editor.views.list list.id %}" >Finished Editing</a>
    {% else %}
<!--
    <input class="btn btn-primary btn-success" type="submit" value="Generate" /> 
-->
    <button type="submit" class="btn btn-primary btn-large btn-success">{% icon "icon-share" %} Generate This Problem</button>
    {% endif %}
    </div>
</div>

</form>
{% endblock pageform %}

{% block pagecontent %}
{% include "editable_problem.html" %}
{% endblock pagecontent%}

templates/formerrors.html
{% extends "base.html" %}

{% block content %}
{% if form.errors %}
<div id="form-error">
    <p>The operation could not be performed because one or more error(s) occurred.<br />Please try again after making the following changes:</p>
    <ul>
    {% for field in form %}
        {% if field.errors %}
            <li><p> For {{field.name}}:</p> {{field.errors|striptags }}</li>
        {% endif %} 
    {% endfor %}
    </ul>
</div>
{% endif %}
{% endblock %}

templates/import_template_main.html
{% extends "main.html" %}

{% block mainjs %}
<script type="text/javascript"> 
$(document).ready(function() {
  $('#saveform').submit(function() {
     var question_html = $('#question').html();
     $('#id_question').val($.trim(question_html));
     var answer_html = $('#answer').html();
     $('#id_answer').val($.trim(answer_html));
  });
});
</script>
<script type="text/javascript"> 
function setup_pagecontent() {
    setup_pagecontent_ajax_links();
}
</script>
<script type="text/javascript" src="/media/mathplosion.js"></script>
<script type="text/javascript"> 
var json_params={{template.params|safe}};
</script>
{{template.javascript|safe}}
{{block.super}}
{% endblock mainjs %}

{% block pagenav%}
{% endblock pagenav%}

{% block pageheader %}
<div class="row-fluid">
    <div id="title">
        <div class="span12">
                <h2>Template Filename: {{template.filename}} </h2>
        </div>
    </div>
</div>
{% endblock pageheader %}

{% block pageform%}
    <div class="container">
        <form class="well form-horizontal" id="saveform" method="post" action="{% url save_import_template tid=tid %}">
            {% csrf_token %}
            {{templateform.question}}
            {{templateform.answer}} 

            <fieldset>
                <div class="control-group">
                    <label class="control-label" for="id_name">Name:</label>
                    <div class="controls">
                        {{templateform.name}}  
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_tags">Tags:</label>
                    <div class="controls">
                        {{templateform.tags}}
                    </div>
                </div>
                <div class="form-actions">
                    <input name="import" class="btn btn-primary" type="submit" value="Import To Mathplosion" /> 
                    <a class="btn" title="Cancel" href="{% url editor.views.templates %}" >Cancel</a>
                </div>
            </fieldset>
        </form>
  </div>
<div class="row-fluid">
    <div class="span12">
        <h3> Below is what your problem will look like in Mathplosion: </h3>
        <p> Edit file first, then refresh here before importing it. </p>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">
        <form id="formrefresh" class="form-inline">
{% if template.filename|slice:":17" == "http://jsbin.com/" %}
        <a class="btn btn-small" title="Edit In Jsbin"  
        target="_blank" href="{{template.filename}}/latest/edit#html,live" >
        <i class="icon-edit"></i> Edit In Jsbin</a>
{% endif %}
        <a class="btn btn-small btn-success" title="Refresh Preview" href="" >Refresh Preview</a>
        </form> 
    </div>
</div>
{% endblock pageform%}

{% block pagecontent %}
<h2>Preview of Your Problem</h2>

<form id="form" class="well form-inline">
<div class="row-fluid">
    <div class="span12">
        <div id="formparams">
        <!-- params will be put in via jquery by mathplosion.js -->
        </div>
    </div>
</div>
</form>

<div id="template{{template.id}}" class="problem blackwhite">
<h3 class="blackwhite" >Question</h3>
  <div id="question">
    {{template.question_template|safe}}
  </div>
<h3 class="blackwhite" >Answer</h3>
  <div id="answer">
    {{template.answer_template|safe}}
  </div>
</div>
{% endblock pagecontent %}

templates/index.html
{% extends "base.html" %}

{%block content %}
<div class="container-fluid">
{% include "herosmall.html" %}
</div>
{% endblock content %}

templates/list_main.html
{% extends "main.html" %}
{% load editor_extras %}

{% block mainjs %}
<script type="text/javascript"> 
function setup_pagecontent() {
    setup_pagecontent_ajax_links();
    setup_answer_triggers();
}

function setup_answer_triggers() {
    $('.trigger').click(function(event){

        var trigger_id = $(this).attr('id');
        var target_id = trigger_id.replace("trigger","target");
        $('#' + target_id).toggle();

        var icon = $(this).find('i')
        if (icon.hasClass('icon-plus')) {
            icon.removeClass('icon-plus');
            icon.addClass('icon-minus');
        }
        else if (icon.hasClass('icon-minus')) {
            icon.removeClass('icon-minus');
            icon.addClass('icon-plus');
        }
    });
}

function set_active_tab_click (tab, tab1, tab2) {
    tab.click(function(){
        tab1.removeClass("active");
        tab2.removeClass("active");
        tab.addClass("active");
    });
}

$(document).ready(function() {
   //console.log("doc ready in list called");

   // Set up full page first.
   // The tabs
   var edit = $('#edit_mode');
   var full = $('#full_mode');
   var preview = $('#preview_mode');
   edit.find('a').click(ajax_link_click);
   preview.find('a').click(ajax_link_click);
   full.find('a').click(ajax_link_click);
   set_active_tab_click(edit,preview,full); 
   set_active_tab_click(full,edit,preview); 
   set_active_tab_click(preview,edit,full); 
});
</script>
{{block.super}}
{% endblock mainjs %}

{% block tabs%}
<div class="span6">
    <ul class="nav nav-pills">
          <li id="edit_mode" class="active"><a class="ajax_link" href="{% url ajax_list id=list.id mode="edit" %}">Edit</a></li>
          <li id="preview_mode" ><a class="ajax_link" href="{% url ajax_list id=list.id mode="preview" %}">Preview Questions</a></li>
          <li id="full_mode"><a class="ajax_link" href="{% url ajax_list id=list.id mode="full" %}">Preview Full</a></li>
    </ul>
</div>
{% endblock tabs%}

{% block menus%}
<div class="span6">
      <div class="btn-group pull-right">
      <a title="Delete All Problems from This Problem Set" class="btn btn-mini btn-warning" href="{% url editor.views.delete_problems list.id %}">Delete Problems</a>
      <a title="Change Settings for This Problem Set" class="btn btn-mini" href="{% url editor.views.change_list_settings list.id %}">Settings</a>
    </div>
</div>
{% endblock menus%}

{% block title %}
<div class="span6">
    <h2>{{ list.name }}</h2>
</div>
{% endblock title %}

{% block actionarea %}
<div class="span6">
      <div class="pull-right">
        <a title="Add Problems to {{list.name}} ..." class="btn btn-primary btn-large" href="{% url templates_id id=list.id %}">Add Problems... </a>
        <a title="Generate this Problem Set" class="btn btn-large btn-success" href="{% url editor.views.view_list list.id %}">
          {% icon "icon-share" %} Generate</a>
      </div>
</div>
{% endblock actionarea %}

{% block pagecontent %}
<!-- first time it is included directly, thereafter it is loaded by ajax-->
{% include "ajax_list.html" %}
{% endblock pagecontent %}

templates/newlist_main.html
{% extends "main.html" %}

{% block title %}
<div class="span12">
  <h2> Create a New Problem Set </h2>
</div>
{% endblock title %}          

{% block pageform%}
  <form method="post" action="{% url editor.views.create_list %}">
  {% csrf_token %}
<p> Name: {{listform.name}} </p>
<p> Tags: {{listform.tags}} </p>
  <input class="create" type="submit" value="Create Problem Set">
  </form>
</div>
{% endblock pageform%}

templates/problem_params.html
{% block problemparams %}
{% if problem.params %}
<script type="text/javascript" src="/media/mathplosion.js"></script>
<script type="text/javascript"> 
var json_params={{problem.params|safe}};
</script>
{{problem.javascript|safe}}
{% endif %}
{% endblock problemparams %}

templates/selenium_save.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://mathplosion.com/" />
<title>Saving Templates</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">Saving Templates</td></tr>
</thead><tbody>

{% for template in templates %}
<tr>
	<td>clickAndWait</td>
	<td>//li[{{forloop.counter}}]/div/div/a[2]/img</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>name=Test</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>name=Save</td>
	<td></td>
</tr>
{% endfor %}

</tbody></table>
</body>
</html>

templates/share_it_main.html
{% extends "main.html" %}
{% load editor_extras %}

{% block mainjs %}
<script type="text/javascript"> 
function setup_pagecontent() {
    setup_pagecontent_ajax_links();
}

$(document).ready(function() {

    $("input").keypress(function (e) {
        var k = e.keyCode || e.which;
        if (k == 13) {
            update();
            return false; 
        }
    });

    $('a[href="#preview"]').on('show', function (e) {
        var url = "{% url editor.views.output list.id %}";  
        var args = $("#outputform").serialize();
        var iframe = $("#previewframe");
        iframe.height(0);
        iframe.load(function(){
            var iframe_content = iframe.contents().find('body');
            iframe.height(iframe_content.outerHeight(true));
            //iframe.css({ height: iframe_content.outerHeight( true ) });
        });
        iframe.attr("src",url + "?" + args);
    })

});
</script>
{{block.super}}
{% endblock mainjs %}

{% block menus%}
<div class="span12">
      <div class="btn-group pull-right">
        <a title="Back to Editing" class="btn btn-mini" href="{% url editor.views.list list.id %}">Back to Editing</a>
    </div>
</div>
{% endblock menus%}

{% block pageheader %}
<h2>Generate Problem Set</h2>
{% endblock pageheader %}

{% block pagecontent %}
            <ul id="myTab" class="nav nav-pills">
              <li class="active"><a href="#options" data-toggle="tab">Output Options</a></li>
              <li><a href="#preview" data-toggle="tab">Preview of Output</a></li>
            </ul>
            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade in active" id="options">
                <form id="outputform" class="well form-horizontal"  method="get" action="{% url editor.views.output list.id %}">

                 <fieldset>
                    <div class="control-group">
                        <label class="control-label" for="id_name">Title (Optional):</label>
                        <div class="controls">
                            <input type="text" name="name" id="id_name" value="{{list.name}}"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Style</label>
                        <div class="controls">
                          <label class="radio inline">
                            <input type="radio" name="theme" value="no" checked> 
                            No Theme 
                          </label>
                          <label class="radio inline">
                            <input type="radio" name="theme" value="yes"> 
                            Use Theme 
                          </label>
                        </div>
                      </div>
                    <div class="control-group">
                        <label class="control-label">Numbering</label>
                        <div class="controls">
                          <label class="radio inline">
                            <input type="radio" name="style" value="numbered" checked> 
                            Show Numbers 
                          </label>
                          <label class="radio inline">
                            <input type="radio" name="style" value="unnumbered"> 
                            No Numbers 
                          </label>
                        </div>
                      </div>
                      <div class="control-group">
                        <label class="control-label">What To Show</label>
                        <div class="controls">
                          <label class="radio inline">
                            <input type="radio" name="show" id="radio1" value="questions" checked>
                            Questions 
                          </label>
                          <label class="radio inline">
                            <input type="radio" name="show" id="radio2" value="answers">
                            Answers 
                          </label>
                          <label class="radio inline">
                            <input type="radio" name="show" id="radio3" value="both">
                            Both 
                          </label>
                        </div>
                     </div>
                    <div class="form-actions">
                      <button type="submit" class="btn btn-primary btn-large btn-success">{% icon "icon-share" %} Generate This Problem Set</button>
                    </div>
                 </fieldset>
                </form> 
              </div>
              <div class="tab-pane fade" id="preview">
                  <div id="iframecontainer">
                    <iframe id="previewframe" width="100%" height="200" frameborder="0" scrolling="no"> </iframe> 
                  </div>
              </div>
            </div>


{% endblock pagecontent %}

templates/tags.html
{% extends "base.html" %}

{%block tags_active %}
class="active"
{%endblock%}

{%block content %}
Tags tab not implemented yet
{%endblock content %}

templates/tagsvideo.html
{% extends "base.html" %}

{% block content %}
<div id="content">
  <div style="margin:20px" class="video">
    <iframe width="852" height="480" src="http://www.youtube.com/embed/qzCMF_newNg" frameborder="0" allowfullscreen></iframe>
  </div>
</div>
{% endblock %}

templates/templates_categories.html
<ul id="myTab" class="nav nav-tabs">
  <li class="active"><a href="#statistics" data-toggle="tab">Statistics</a></li>
  <li><a href="#algebra" data-toggle="tab">Algebra</a></li>
  <li><a href="#geometry" data-toggle="tab">Geometry</a></li>
  <li><a href="#basic" data-toggle="tab">Basic</a></li>
  <li><a href="#demo" data-toggle="tab">Demo</a></li>
</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane fade in active" id="statistics">
{% include "ajax_templates.html" with templates=statistics_templates%}
  </div>
  <div class="tab-pane fade" id="algebra">
{% include "ajax_templates.html" with templates=algebra_templates%}
  </div>
  <div class="tab-pane fade" id="geometry">
{% include "ajax_templates.html" with templates=geometry_templates%}
  </div>
  <div class="tab-pane fade" id="basic">
{% include "ajax_templates.html" with templates=basic_templates%}
  </div>
  <div class="tab-pane fade" id="demo">
{% include "ajax_templates.html" with templates=demo_templates%}
  </div>
</div>